#!/bin/bash
echo "=========================================="
echo "Service Credentials Summary"
echo "=========================================="
echo ""
echo "📊 All Services Status:"
./check_services.py 2>&1 | tail -5
echo ""
echo "=========================================="
echo "🔐 Credentials (from environment):"
echo "=========================================="
echo ""
echo "PostgreSQL (Supabase):"
echo "  Password: $(docker exec supabase-db printenv POSTGRES_PASSWORD 2>/dev/null || echo 'Check .env file')"
echo ""
echo "Supabase Dashboard:"
echo "  Username: $(docker exec supabase-db printenv DASHBOARD_USERNAME 2>/dev/null || echo 'Check .env file')"
echo "  Password: $(docker exec supabase-db printenv DASHBOARD_PASSWORD 2>/dev/null || echo 'Check .env file')"
echo ""
echo "Flowise:"
echo "  Username: $(docker exec flowise printenv FLOWISE_USERNAME 2>/dev/null || echo 'Not set - may allow access without auth')"
echo "  Password: $(docker exec flowise printenv FLOWISE_PASSWORD 2>/dev/null || echo 'Not set - may allow access without auth')"
echo ""
echo "Neo4j:"
echo "  Auth: $(docker exec localai-neo4j-1 printenv NEO4J_AUTH 2>/dev/null || echo 'Check .env file - format: neo4j/password')"
echo ""
echo "MinIO (default if not changed):"
echo "  Username: minioadmin"
echo "  Password: minioadmin"
echo ""
echo "=========================================="
echo "🌐 Service URLs:"
echo "=========================================="
echo "n8n:              http://localhost:6678"
echo "Supabase Studio:  http://localhost:8000"
echo "Open WebUI:       http://localhost:8080"
echo "Flowise:          http://localhost:3001"
echo "Langfuse:         http://localhost:4000"
echo "Qdrant:           http://localhost:7333"
echo "Neo4j Browser:    http://localhost:7474"
echo "SearXNG:          http://localhost:8081"
echo "MinIO Console:    http://localhost:9011"
echo "Ollama API:       http://localhost:12434"
echo ""
echo "=========================================="
echo "💡 To view all credentials, check .env file:"
echo "   cat .env | grep -E 'PASSWORD|USERNAME|AUTH'"
echo "=========================================="
